# Generated by Django 3.1.7 on 2021-04-22 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('profile_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Page.page')),
                ('release_date', models.DateField(null=True)),
                ('rating', models.IntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
            bases=('Page.page',),
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Page.page')),
                ('artist_type', models.CharField(default='', max_length=255)),
                ('begin_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            bases=('Page.page',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Page.page')),
                ('release_date', models.DateField(null=True)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('artists', models.ManyToManyField(to='Page.Artist')),
                ('music_album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.album')),
            ],
            bases=('Page.page',),
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('content', models.CharField(default='', max_length=255)),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.music')),
            ],
        ),
    ]
