# Generated by Django 3.1.7 on 2021-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, to='Page.Album'),
        ),
    ]
