# Generated by Django 3.1.7 on 2021-04-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0002_auto_20210410_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
