# Generated by Django 3.1.7 on 2021-04-10 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0003_auto_20210410_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='music',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
