# Generated by Django 3.1.7 on 2021-03-29 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profie_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profie_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('artist_type', models.CharField(max_length=100)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commented_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('context', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('commented', models.ManyToManyField(to='hex_clan.Commented_Section')),
                ('liked_section', models.ManyToManyField(to='hex_clan.Liked_Section')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profie_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('url', models.URLField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.album')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.artist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('avatar', models.ImageField(upload_to=None)),
                ('album_ratings', models.ManyToManyField(related_name='_user_album_ratings_+', to='hex_clan.Album')),
                ('favorites_albums', models.ManyToManyField(to='hex_clan.Album')),
                ('favorites_artists', models.ManyToManyField(to='hex_clan.Artist')),
                ('favorites_musics', models.ManyToManyField(related_name='_user_favorites_musics_+', to='hex_clan.Music')),
                ('music_ratings', models.ManyToManyField(to='hex_clan.Music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
        migrations.AddField(
            model_name='music',
            name='lyric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.lyric'),
        ),
        migrations.AddField(
            model_name='music',
            name='urls',
            field=models.ManyToManyField(to='hex_clan.URL'),
        ),
        migrations.AddField(
            model_name='liked_section',
            name='likes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.user'),
        ),
        migrations.AddField(
            model_name='commented_section',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hex_clan.user')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='_artist_albums_+', to='hex_clan.Music'),
        ),
        migrations.AddField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
        migrations.AddField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
    ]
