# Generated by Django 3.1.7 on 2021-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex_clan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(null=True, related_name='_artist_albums_+', to='hex_clan.Music'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='begin_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(null=True, to='hex_clan.User'),
        ),
    ]
