# Generated by Django 3.1.7 on 2021-03-30 16:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hex_clan', '0002_auto_20210330_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='profie_type',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='profie_type',
        ),
        migrations.RemoveField(
            model_name='music',
            name='profie_type',
        ),
        migrations.RemoveField(
            model_name='music',
            name='url',
        ),
        migrations.AlterField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(null=True, to='hex_clan.User'),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='music',
            name='album',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hex_clan.album'),
        ),
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(null=True, to='hex_clan.User'),
        ),
        migrations.AlterField(
            model_name='music',
            name='lyric',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hex_clan.lyric'),
        ),
        migrations.AlterField(
            model_name='music',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='music',
            name='urls',
            field=models.ManyToManyField(null=True, to='hex_clan.URL'),
        ),
    ]
