# Generated by Django 3.1.7 on 2021-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex_clan', '0004_auto_20210330_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='_artist_albums_+', to='hex_clan.Music'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
        migrations.AlterField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
        migrations.AlterField(
            model_name='music',
            name='urls',
            field=models.ManyToManyField(to='hex_clan.URL'),
        ),
    ]
