# Generated by Django 3.1.7 on 2021-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex_clan', '0005_auto_20210330_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='likes',
            field=models.ManyToManyField(to='hex_clan.User'),
        ),
    ]
