# Generated by Django 3.1.7 on 2021-03-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hex_clan', '0008_auto_20210330_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='profie_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='profie_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='music',
            name='profie_type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
