# Generated by Django 3.1.7 on 2021-04-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Page', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lyrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('music', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.music')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('likes', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('lyric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.lyrics')),
            ],
        ),
        migrations.CreateModel(
            name='Commented_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('context', models.CharField(default='', max_length=255)),
                ('lyric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Lyrics.lyrics')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
