# Generated by Django 3.1.7 on 2021-04-02 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lyrics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commented_section',
            name='user',
        ),
        migrations.AddField(
            model_name='commented_section',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='liked_section',
            name='likes',
        ),
        migrations.AddField(
            model_name='liked_section',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
