# Generated by Django 3.1.7 on 2021-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0002_auto_20210601_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='context',
            field=models.JSONField(),
        ),
    ]
