# Generated by Django 3.1.7 on 2021-06-08 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lyrics', '0003_auto_20210606_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commented_section',
            name='user',
        ),
        migrations.AddField(
            model_name='commented_section',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
