# Generated by Django 3.1.7 on 2021-06-08 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lyrics', '0004_auto_20210608_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='commented_section',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
