# Generated by Django 3.1.7 on 2021-04-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('avatar', models.ImageField(upload_to=None)),
                ('album_ratings', models.ManyToManyField(related_name='user_albumrating', to='Page.Album')),
                ('favorites_albums', models.ManyToManyField(to='Page.Album')),
                ('favorites_artists', models.ManyToManyField(to='Page.Artist')),
                ('favorites_musics', models.ManyToManyField(related_name='user_favoritemusic', to='Page.Music')),
                ('music_ratings', models.ManyToManyField(to='Page.Music')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(default='', max_length=255)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
