# Generated by Django 3.1.7 on 2021-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album_comment',
            name='context',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='artist_comment',
            name='context',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='music_comment',
            name='context',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/Images/default.jpg', null=True, upload_to='Images/'),
        ),
    ]
