# Generated by Django 3.1.7 on 2021-04-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210430_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
