# Generated by Django 3.1.7 on 2021-05-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_top_album_rating_top_artist_rating_top_music_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_artist_followings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(default='', max_length=255)),
                ('following_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='album_like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist_like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='artist_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='music_like',
            name='user',
        ),
        migrations.DeleteModel(
            name='top_artist_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='artist_ratings',
        ),
        migrations.DeleteModel(
            name='album_like',
        ),
        migrations.DeleteModel(
            name='artist_like',
        ),
        migrations.DeleteModel(
            name='artist_rating',
        ),
        migrations.DeleteModel(
            name='music_like',
        ),
    ]
