# Generated by Django 3.1.7 on 2021-04-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0001_initial'),
        ('User', '0003_auto_20210405_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='album_ratings',
            field=models.ManyToManyField(blank=True, related_name='user_albumrating', to='Page.Album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites_albums',
            field=models.ManyToManyField(blank=True, to='Page.Album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites_artists',
            field=models.ManyToManyField(blank=True, to='Page.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites_musics',
            field=models.ManyToManyField(blank=True, related_name='user_favoritemusic', to='Page.Music'),
        ),
        migrations.AlterField(
            model_name='user',
            name='music_ratings',
            field=models.ManyToManyField(blank=True, to='Page.Music'),
        ),
    ]
