# Generated by Django 3.1.7 on 2021-05-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210514_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='top_album_rating',
            new_name='total_album_rating',
        ),
        migrations.RenameModel(
            old_name='top_artist_followings',
            new_name='total_artist_followings',
        ),
        migrations.RenameModel(
            old_name='top_music_rating',
            new_name='total_music_rating',
        ),
    ]
