# Generated by Django 3.1.7 on 2021-05-09 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210507_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_album_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(default='', max_length=255)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('vote_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='top_artist_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(default='', max_length=255)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('vote_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='top_music_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(default='', max_length=255)),
                ('rating', models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('vote_num', models.IntegerField(default=0)),
            ],
        ),
    ]
