# Generated by Django 3.1.7 on 2021-05-24 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20210514_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='album_ratings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites_albums',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites_artists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favorites_musics',
        ),
        migrations.RemoveField(
            model_name='user',
            name='music_ratings',
        ),
        migrations.RemoveField(
            model_name='album_favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='album_favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='album_rating',
            name='user',
        ),
        migrations.AddField(
            model_name='album_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='artist_favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='artist_favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='music_favorite',
            name='user',
        ),
        migrations.AddField(
            model_name='music_favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='music_rating',
            name='user',
        ),
        migrations.AddField(
            model_name='music_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
