# Generated by Django 3.1.7 on 2021-04-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
